services:
  auth:
    container_name: auth
    restart: always
    build:
      context: auth/
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./auth:/code
    environment:
      SECRET_KEY: <SECRET_KEY>
      POSTGRES_HOST: auth-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
      REDIS_HOST: auth-redis
    networks:
      - shared_network
    depends_on:
      - auth-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-postgres:
    container_name: auth-postgres
    image: postgres:14.1
    ports:
      - 5454:5432
    volumes:
      - auth-postgres-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - shared_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-redis:
    image: "redis:5.0.5-alpine"
    container_name: auth-redis
    ports:
      - "6380:6379"
    volumes:
      - auth-redis-volume:/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - TZ=UTC
    networks:
      - shared_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  auth-postgres-vol:
    name: auth-postgres-vol
  auth-redis-volume:
    name: auth-redis-volume

networks:
  shared_network:
